# Generated by Django 3.2.9 on 2021-11-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipContent', models.TextField()),
                ('tipType', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='tip_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='tip_id',
            field=models.IntegerField(default=0),
        ),
    ]
